import "./styles.css";

export {
  applySlotOperationChanges,
  applySlotOperationValueUpdates,
  assertExactMatrixEqual,
  assertExactMatrixShape,
  assertExactPositionSet,
  decodePositionInMatrix,
  findMatrixValuePositions,
  forEachMatrixCell,
  requireSafeInteger,
  requireSafeIntegerArray,
  requireExactlyOne,
  parseExactPositionPairs,
  parseTransferRoutes,
  slotOperationPositionKey,
  validatePositionInMatrix,
  compileConfiguredSlotRoundOperationPlanV2,
  createGameConfig,
  createBuiltinSlotOperationDefinitionsV2,
  finalizeSlotOperationPlanV2,
  createSlotOperationServerView,
  selectServerComponentSource,
  genDropdownOperation,
  genChg,
  genRefillOperation,
  genRemoveOperation,
  genSpinOperation,
  genWinOperation,
  createSlotOperationSnapshot,
  compileSlotCascadeFacts,
  deriveSlotCascadeDropdownValues,
} from "@slotclientengine/logiccore";
export {
  createSceneLayoutPackageResource,
  createSceneLayoutPackageRuntime,
  createSceneLayoutPresentationSurface,
} from "@slotclientengine/rendercore";
export type {
  SceneLayoutLayerId,
  SceneLayoutPackageResource,
  SceneLayoutPackageRuntime,
  SceneLayoutPresentationSurface,
  SceneLayoutRuntimeResource,
} from "@slotclientengine/rendercore";
export type {
  SlotOperationPlanV2,
  SlotOperationSource,
  SlotOperationDefinitionV2,
  SlotOperationDraftV2,
  SlotStateMutationOperation,
  SlotOperationV2,
  SlotOperationSnapshot,
  SlotStateMutationDraftV2,
  SlotChgDraftV2,
  SlotChgDrivenPayload,
  SlotChgOperation,
  SlotChgPayload,
  SlotChgPositionPayload,
  SlotChgRoute,
  SlotChgTransferPayload,
  SlotRoundCapability,
  SlotRoundCompileContext,
  SlotRoundDropdownStepPlan,
  SlotRoundMovementPlan,
  SlotRoundOccurrence,
  SlotRoundOccurrenceSnapshot,
  SlotRoundPosition,
  SlotRoundPresentationValue,
  SlotRoundRefillStepPlan,
  SlotRoundSettledCompileContext,
  SlotRoundSettledSceneCompileContext,
  SlotRoundSettledTransformChangeDraft,
  SlotRoundSettledTransformOccurrenceChange,
  SlotRoundSettledTransformRelocation,
  SlotRoundSettledTransformRelocationDraft,
  SlotRoundSettledTransformDraft,
  SlotRoundSettledTransformStepPlan,
  SlotRoundSettledValueDraft,
  SlotRoundValueMatrix,
  SlotRoundWinGroupPlan,
  SlotRoundWinStepPlan,
  SlotCascadeFacts,
  SlotCascadeCanDropOccurrence,
  SlotCascadeMovementFact,
  SlotCascadeOccurrenceContext,
  SlotCascadeValueCommit,
  SlotCascadeValueMatrix,
} from "@slotclientengine/logiccore";
export { createSlotGameFramework, buildSpinParams } from "./framework.js";
export {
  SlotGameConfigError,
  SlotGameRuntimeError,
  toSlotGameError,
} from "./errors.js";
export { SlotGameStateStore } from "./state.js";
export {
  SlotGameLiveSession,
  createSlotcraftClientOptions,
  prepareSlotGameLiveSession,
  requireFiniteBalance,
  validateLiveServerUrl,
} from "./session.js";
export {
  createSlotGameLogicResult,
  type SlotGameLogicResult,
} from "./logic-result.js";
export {
  createSlotGameRoundContext,
  type SlotGameRoundContext,
} from "./round-context.js";
export { shouldCollectFinalResult } from "./collect.js";
export {
  findComponentSteps,
  getComponentOtherScenesByName,
  getComponentResultsByName,
  getComponentScenesByName,
  getComponentWinResultGroupsByName,
} from "./component-helpers.js";
export type {
  ComponentWinResultGroup,
  ComponentWinResultPositionValidationContext,
  ComponentWinResultPositionValidator,
  GameConfigPaytableEntry,
  GameLogic,
  GameLogicMeta,
  GameLogicStep,
  LogicGameConfig,
  LogicComponent,
  LogicReels,
  OtherSceneMatrix,
  ReelStopYOptions,
  SceneMatrix,
  SlotGameAdapter,
  SlotGameBetOption,
  SlotGameClientFactory,
  SlotGameClientLike,
  SlotGameFocusFramePolicy,
  SlotGameFramePolicy,
  SlotGameFramework,
  SlotGameFrameworkOptions,
  SlotGameInitialState,
  SlotGameLiveConfig,
  SlotGameLiveSessionLike,
  SlotGameLogicFactory,
  SlotGameMaximizedFocusFramePolicy,
  SlotGameMountContext,
  SlotGamePerformanceEvent,
  SlotGamePerformanceObserver,
  SlotGamePerformancePhase,
  SlotGamePerformanceTraceKind,
  SlotGameRngConsoleOptions,
  SlotGameSpinRequest,
  SlotGameSpinState,
  SlotGameStateSnapshot,
  SlotGameUi,
  SlotGameUiCommands,
  SlotGameUiCreateContext,
  SlotGameUiElements,
  SlotGameUiFactory,
  SlotGameViewportListener,
  SlotGameViewportSnapshot,
  WinResult,
  WinResultPosition,
} from "./types.js";
export {
  createSceneLayoutSlotGameTemplate,
  getServerBetMethodComponentCatalog,
  inspectSceneLayoutPackageInput,
  inspectSceneLayoutTemplateInputs,
  parseSceneLayoutSlotTemplateConfig,
  parseServerGameAuthoringSummary,
  suggestSlotRoundFlow,
  validateSlotRoundFlowCatalogCompatibility,
} from "./scene-layout-template/index.js";
export { createSpinePopupPlayer } from "@slotclientengine/rendercore/popup";
export type {
  PopupManifest,
  PopupManifestV1,
  PopupManifestV2,
  PopupHostPlacement,
  PopupPresentationSnapshot,
  SpinePopupManifestV1,
  SpinePopupManifestV2,
  SpinePopupPhase,
  SpinePopupPlayer,
  SpinePopupSnapshot,
} from "@slotclientengine/rendercore/popup";
export type {
  SceneLayoutSlotTemplateConfigV1,
  SceneLayoutTemplateCredential,
  SceneLayoutTemplateReadinessSnapshot,
  ServerGameAuthoringSummary,
  SlotRoundFlowProfileV1,
  SlotRoundFlowSuggestions,
  SlotTemplatePresentationProfileV1,
} from "./scene-layout-template/index.js";
