import "./styles.css";

export type {
  AudioPlaybackHandle,
  AudioPlaybackState,
  AudioRuntimeSnapshot,
} from "@slotclientengine/audiocore/core";

export {
  applySlotOperationChanges,
  applySlotOperationValueUpdates,
  assertExactMatrixEqual,
  assertExactMatrixShape,
  assertExactPositionSet,
  decodePositionInMatrix,
  findMatrixValuePositions,
  forEachMatrixCell,
  requireSafeInteger,
  requireSafeIntegerArray,
  requireExactlyOne,
  parseExactPositionPairs,
  parseTransferRoutes,
  parseFeatureBar2Data,
  slotOperationPositionKey,
  validatePositionInMatrix,
  compileConfiguredSlotRoundOperationPlanV2,
  createGameConfig,
  createBuiltinSlotOperationDefinitionsV2,
  finalizeSlotOperationPlanV2,
  createSlotOperationServerView,
  selectServerComponentSource,
  genDropdownOperation,
  genChg,
  genRefillOperation,
  genRemoveOperation,
  genSpinOperation,
  genWinOperation,
  createSlotOperationSnapshot,
  compileSlotCascadeFacts,
  deriveSlotCascadeDropdownValues,
} from "@slotclientengine/logiccore";
export {
  createSceneLayoutPackageResource,
  createSceneLayoutPackageRuntime,
  createSceneLayoutPresentationSurface,
  formatGameLayoutRuntimeAddress,
  parseGameLayoutRuntimeAddress,
} from "@slotclientengine/rendercore/scene-layout/core";
export {
  attachRenderObjectToSpineSlot,
  createRenderObjectMotionRuntime,
} from "@slotclientengine/rendercore";
export type {
  SceneLayoutLayerId,
  SceneLayoutPackageResource,
  SceneLayoutPackageRuntime,
  SceneLayoutPopupCloseOptions,
  SceneLayoutPopupOpenRequest,
  SceneLayoutPopupSession,
  SceneLayoutPopupSessionState,
  SceneLayoutPresentationSurface,
  SceneLayoutRuntimeResource,
  SceneLayoutNodeRenderLayerPlacement,
  SceneLayoutRenderLayerRef,
  SceneLayoutRenderObject,
  SceneLayoutRenderObjectMotion,
  SceneLayoutRenderObjectMotionAxis,
  SceneLayoutRenderObjectMotionOptions,
  SceneLayoutRenderObjectMotionSelfAlignment,
  SceneLayoutRenderObjectMotionTarget,
  SceneLayoutRenderObjectPropertyAnimation,
  SceneLayoutSpineLoopRenderObject,
  SceneLayoutSpineAnimationPlayOptions,
  SceneLayoutSpineSlotObjectAttachment,
  SceneLayoutSpineSlotObjectBinding,
  SceneLayoutPoint,
  SceneLayoutPointSelector,
  RenderAlignment,
  GameLayoutRuntimeAddress,
  GameLayoutRuntimeAddressDescriptor,
  GameLayoutRuntimeAddressKind,
  GameLayoutRuntimeAddresses,
  GameLayoutRuntimeEndpoint,
  GameLayoutRuntimeEvent,
  GameLayoutRuntimeEventListener,
  GameLayoutRuntimeWaitOptions,
} from "@slotclientengine/rendercore/scene-layout/core";
export type {
  AttachRenderObjectToSpineSlotOptions,
  ImgNumberRenderObject,
  PresentationObjectAnimationOptions,
  RenderObject,
  RenderObjectFadeOptions,
  RenderObjectLayer,
  RenderObjectLayerAddAtOptions,
  RenderObjectLayerMove,
  RenderObjectLayerMoveOptions,
  RenderObjectPlayOptions,
  RenderObjectMotion,
  RenderObjectMotionAnimation,
  RenderObjectMotionEasing,
  RenderObjectMotionPath,
  RenderObjectMotionRuntime,
  RenderObjectMotionTarget,
  RenderPoint,
  RenderScale,
  SpineSlotRenderObjectAttachment,
} from "@slotclientengine/rendercore";
export type {
  SymbolCellBounds,
  SymbolGroup,
} from "@slotclientengine/rendercore/symbol/core";
export type {
  SlotOperationPlanV2,
  SlotOperationSource,
  SlotOperationDefinitionV2,
  SlotOperationDraftV2,
  SlotStateMutationOperation,
  SlotOperationV2,
  SlotOperationSnapshot,
  SlotStateMutationDraftV2,
  SlotChgDraftV2,
  SlotChgDrivenPayload,
  SlotChgOperation,
  SlotChgPayload,
  SlotChgPositionPayload,
  SlotChgRoute,
  SlotChgTransferPayload,
  SlotRoundCapability,
  SlotRoundCompileContext,
  SlotRoundDropdownStepPlan,
  SlotRoundMovementPlan,
  SlotRoundOccurrence,
  SlotRoundOccurrenceSnapshot,
  SlotRoundPosition,
  SlotRoundPresentationValue,
  SlotRoundRefillStepPlan,
  SlotRoundSettledCompileContext,
  SlotRoundSettledSceneCompileContext,
  SlotRoundSettledTransformChangeDraft,
  SlotRoundSettledTransformOccurrenceChange,
  SlotRoundSettledTransformRelocation,
  SlotRoundSettledTransformRelocationDraft,
  SlotRoundSettledTransformDraft,
  SlotRoundSettledTransformStepPlan,
  SlotRoundSettledValueDraft,
  SlotRoundValueMatrix,
  SlotRoundWinGroupPlan,
  SlotRoundWinStepPlan,
  SlotCascadeFacts,
  SlotCascadeCanDropOccurrence,
  SlotCascadeMovementFact,
  SlotCascadeOccurrenceContext,
  SlotCascadeValueCommit,
  SlotCascadeValueMatrix,
} from "@slotclientengine/logiccore";
export { createSlotGameFramework, buildSpinParams } from "./framework.js";
export {
  SlotGameConfigError,
  SlotGameRuntimeError,
  toSlotGameError,
} from "./errors.js";
export { SlotGameStateStore } from "./state.js";
export {
  SlotGameLiveSession,
  createSlotcraftClientOptions,
  prepareSlotGameLiveSession,
  requireFiniteBalance,
  validateLiveServerUrl,
} from "./session.js";
export {
  createSlotGameLogicResult,
  type SlotGameLogicResult,
} from "./logic-result.js";
export {
  createSlotGameRoundContext,
  type SlotGameRoundContext,
} from "./round-context.js";
export { shouldCollectFinalResult } from "./collect.js";
export {
  findComponentSteps,
  getComponentOtherScenesByName,
  getComponentResultsByName,
  getComponentScenesByName,
  getComponentWinResultGroupsByName,
} from "./component-helpers.js";
export type {
  ComponentWinResultGroup,
  ComponentWinResultPositionValidationContext,
  ComponentWinResultPositionValidator,
  GameConfigPaytableEntry,
  FeatureBar2Data,
  GameLogic,
  GameLogicMeta,
  GameLogicStep,
  LogicGameConfig,
  LogicComponent,
  LogicReels,
  OtherSceneMatrix,
  ReelStopYOptions,
  SceneMatrix,
  SlotGameAdapter,
  SlotGameBetOption,
  SlotGameClientFactory,
  SlotGameClientLike,
  SlotGameFocusFramePolicy,
  SlotGameFramePolicy,
  SlotGameFramework,
  SlotGameFrameworkOptions,
  SlotGameInitialState,
  SlotGameLiveConfig,
  SlotGameLiveSessionLike,
  SlotGameLogicFactory,
  SlotGameMaximizedFocusFramePolicy,
  SlotGameMountContext,
  SlotGamePerformanceEvent,
  SlotGamePerformanceObserver,
  SlotGamePerformancePhase,
  SlotGamePerformanceTraceKind,
  SlotGameRngConsoleOptions,
  SlotGameSpinRequest,
  SlotGameSpinState,
  SlotGameStateSnapshot,
  SlotGameUi,
  SlotGameUiCommands,
  SlotGameUiCreateContext,
  SlotGameUiElements,
  SlotGameUiFactory,
  SlotGameViewportListener,
  SlotGameViewportSnapshot,
  WinResult,
  WinResultPosition,
} from "./types.js";
export {
  createSceneLayoutSlotGameTemplate,
  getServerBetMethodComponentCatalog,
  inspectSceneLayoutPackageInput,
  inspectSceneLayoutTemplateInputs,
  parseSceneLayoutSlotTemplateConfig,
  parseServerGameAuthoringSummary,
  suggestSlotRoundFlow,
  validateSlotRoundFlowCatalogCompatibility,
} from "./scene-layout-template/index.js";
export { createSpinePopupRuntime } from "@slotclientengine/rendercore/popup/core";
export type {
  PopupManifest,
  PopupManifestV1,
  PopupManifestV2,
  PopupManifestV3,
  PopupManifestV4,
  PopupManifestV5,
  PopupLayerAttachment,
  SpinePopupManifestV1,
  SpinePopupManifestV2,
  SpinePopupManifestV3,
  SpinePopupManifestV4,
  SpinePopupManifestV5,
} from "@slotclientengine/rendercore/popup/data";
export type {
  PopupHostPlacement,
  PopupPresentationSnapshot,
  SpinePopupPhase,
  SpinePopupRuntime,
} from "@slotclientengine/rendercore/popup/core";
export type {
  SceneLayoutSlotTemplateConfigV1,
  SceneLayoutTemplateCredential,
  SceneLayoutTemplateReadinessSnapshot,
  ServerGameAuthoringSummary,
  SlotRoundFlowProfileV1,
  SlotRoundFlowSuggestions,
  SlotTemplatePresentationProfileV1,
} from "./scene-layout-template/index.js";
