import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { format } from "prettier";
import {
  assertExtension,
  findRepoRoot,
  toImportSpecifierFromRoot,
} from "./path-utils.js";
import { loadGameStaticYamlConfig } from "./yaml-loader.js";
import type {
  BuildGameStaticResolvedOptions,
  BuildGameStaticResult,
  GameStaticYamlArtVariant,
  GameStaticYamlConfig,
  GameStaticYamlFeatureBarConfig,
  GameStaticYamlLoadingResource,
  GameStaticYamlSkinConfig,
} from "./types.js";

export async function generateGameStaticConfigFile(
  options: BuildGameStaticResolvedOptions,
): Promise<BuildGameStaticResult> {
  assertExtension(options.outPath, [".ts"], "--out");
  const rootDir = resolve(options.rootDir || findRepoRoot());
  const inputPath = normalizeOptionPath(rootDir, options.inputPath);
  const outPath = normalizeOptionPath(rootDir, options.outPath);
  const loadingOutPath = options.loadingOutPath
    ? normalizeOptionPath(rootDir, options.loadingOutPath)
    : undefined;
  const config = loadGameStaticYamlConfig({ rootDir, inputPath });
  if (config.gameId !== options.gameId) {
    throw new Error(
      `--game 必须与 YAML gameId 一致：${options.gameId} !== ${config.gameId}`,
    );
  }
  if (config.loading && !loadingOutPath) {
    throw new Error("YAML 包含 loading 配置时必须提供 --loading-out。");
  }
  if (loadingOutPath && !config.loading) {
    throw new Error("--loading-out 需要 YAML 提供 loading.resources。");
  }
  const generated = await generateGameStaticConfigModule({
    rootDir,
    outPath: resolve(rootDir, outPath),
    config,
  });
  const loadingGenerated = loadingOutPath
    ? await generateGameLoadingConfigModule({
        rootDir,
        outPath: resolve(rootDir, loadingOutPath),
        config,
      })
    : undefined;
  const absoluteOutPath = resolve(rootDir, outPath);
  const absoluteLoadingOutPath = loadingOutPath
    ? resolve(rootDir, loadingOutPath)
    : undefined;

  if (options.check) {
    const existing = existsSync(absoluteOutPath)
      ? readFileSync(absoluteOutPath, "utf8")
      : "";
    if (existing !== generated) {
      throw new Error(`生成文件不同步：${outPath}`);
    }
    if (loadingOutPath && absoluteLoadingOutPath && loadingGenerated) {
      const existingLoading = existsSync(absoluteLoadingOutPath)
        ? readFileSync(absoluteLoadingOutPath, "utf8")
        : "";
      if (existingLoading !== loadingGenerated) {
        throw new Error(`生成文件不同步：${loadingOutPath}`);
      }
    }
    return Object.freeze({
      outputPath: outPath,
      generated,
      changed: false,
      ...(loadingOutPath && loadingGenerated
        ? {
            loadingOutputPath: loadingOutPath,
            loadingGenerated,
            loadingChanged: false,
          }
        : {}),
      checked: true,
    });
  }

  const existing = existsSync(absoluteOutPath)
    ? readFileSync(absoluteOutPath, "utf8")
    : "";
  mkdirSync(dirname(absoluteOutPath), { recursive: true });
  if (existing !== generated) {
    writeFileSync(absoluteOutPath, generated, "utf8");
  }
  let loadingChanged: boolean | undefined;
  if (loadingOutPath && absoluteLoadingOutPath && loadingGenerated) {
    assertExtension(loadingOutPath, [".ts"], "--loading-out");
    const existingLoading = existsSync(absoluteLoadingOutPath)
      ? readFileSync(absoluteLoadingOutPath, "utf8")
      : "";
    mkdirSync(dirname(absoluteLoadingOutPath), { recursive: true });
    loadingChanged = existingLoading !== loadingGenerated;
    if (loadingChanged) {
      writeFileSync(absoluteLoadingOutPath, loadingGenerated, "utf8");
    }
  }
  return Object.freeze({
    outputPath: outPath,
    generated,
    changed: existing !== generated,
    ...(loadingOutPath && loadingGenerated
      ? {
          loadingOutputPath: loadingOutPath,
          loadingGenerated,
          loadingChanged,
        }
      : {}),
    checked: false,
  });
}

export async function generateGameStaticConfigModule(options: {
  readonly rootDir: string;
  readonly outPath: string;
  readonly config: GameStaticYamlConfig;
}): Promise<string> {
  const exportName = `${toConstantName(options.config.gameId)}_STATIC_CONFIG`;
  const modulesName = `${toConstantName(options.config.gameId)}_STATIC_SKIN_MODULES`;
  const lines: string[] = [
    "// This file is generated by buildgamestatic. Do not edit by hand.",
    'import { assertSlotGameStaticConfig, type SlotGameStaticConfig } from "@slotclientengine/gameframeworks/static-config";',
    `import rawGameConfig from ${quote(
      toImportSpecifierFromRoot(
        options.rootDir,
        options.outPath,
        options.config.gameConfig,
      ),
    )};`,
  ];
  const importNames = createImportNames(options.config);

  for (const skinId of options.config.supportedSkins) {
    const skin = options.config.skins[skinId];
    const names = importNames[skinId];
    lines.push(
      `import ${names.manifest} from ${quote(
        toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.symbols.manifest,
        ),
      )};`,
      `import ${names.landscapeBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.landscape.background.path,
        )}?url`,
      )};`,
      `import ${names.portraitBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.portrait.background.path,
        )}?url`,
      )};`,
      `import ${names.mainReelBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.mainReelBackground.path,
        )}?url`,
      )};`,
    );
    if (skin.art.variants.landscape.conveyor && names.landscapeConveyor) {
      lines.push(
        `import ${names.landscapeConveyor} from ${quote(
          `${toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.art.variants.landscape.conveyor.path,
          )}?url`,
        )};`,
      );
    }
    if (skin.art.variants.portrait.conveyor && names.portraitConveyor) {
      lines.push(
        `import ${names.portraitConveyor} from ${quote(
          `${toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.art.variants.portrait.conveyor.path,
          )}?url`,
        )};`,
      );
    }
    for (const [featureBarId, featureBar] of Object.entries(
      skin.featureBars ?? {},
    )) {
      const featureBarNames = names.featureBars[featureBarId];
      lines.push(
        `import ${featureBarNames.manifest} from ${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            featureBar.symbols.manifest,
          ),
        )};`,
      );
    }
  }

  lines.push("");
  for (const skinId of options.config.supportedSkins) {
    const names = importNames[skinId];
    const skin = options.config.skins[skinId];
    lines.push(
      `const ${names.symbolModules} = import.meta.glob(${quote(
        toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.symbols.pngGlob,
        ),
      )}, {`,
      "  eager: true,",
      '  import: "default",',
      '  query: "?url"',
      "}) as Record<string, string>;",
    );
    if (skin.symbols.vniProjectGlob && names.vniProjectModules) {
      lines.push(
        `const ${names.vniProjectModules} = import.meta.glob(${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.symbols.vniProjectGlob,
          ),
        )}, {`,
        "  eager: true,",
        '  import: "default"',
        "}) as Record<string, unknown>;",
      );
    }
    if (skin.symbols.vniAssetGlob && names.vniAssetModules) {
      lines.push(
        `const ${names.vniAssetModules} = import.meta.glob(${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.symbols.vniAssetGlob,
          ),
        )}, {`,
        "  eager: true,",
        '  import: "default",',
        '  query: "?url"',
        "}) as Record<string, string>;",
      );
    }
    for (const [featureBarId, featureBar] of Object.entries(
      skin.featureBars ?? {},
    )) {
      const featureBarNames = names.featureBars[featureBarId];
      lines.push(
        `const ${featureBarNames.symbolModules} = import.meta.glob(${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            featureBar.symbols.pngGlob,
          ),
        )}, {`,
        "  eager: true,",
        '  import: "default",',
        '  query: "?url"',
        "}) as Record<string, string>;",
      );
    }
    if (skin.winAmount && names.winAmountProjectModules) {
      lines.push(
        `const ${names.winAmountProjectModules} = import.meta.glob(${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.winAmount.animations.projectGlob,
          ),
        )}, {`,
        "  eager: true,",
        '  import: "default"',
        "}) as Record<string, unknown>;",
      );
    }
    if (skin.winAmount && names.winAmountAssetModules) {
      lines.push(
        `const ${names.winAmountAssetModules} = import.meta.glob(${quote(
          toImportSpecifierFromRoot(
            options.rootDir,
            options.outPath,
            skin.winAmount.animations.assetGlob,
          ),
        )}, {`,
        "  eager: true,",
        '  import: "default",',
        '  query: "?url"',
        "}) as Record<string, string>;",
      );
    }
  }

  lines.push(
    "",
    `export const ${modulesName} = Object.freeze({`,
    ...options.config.supportedSkins.map((skinId) => {
      const names = importNames[skinId];
      return `  ${quote(skinId)}: ${names.symbolModules}`;
    }),
    "} as const);",
    "",
    `export const ${exportName} = Object.freeze({`,
    "  schemaVersion: 1,",
    `  gameId: ${quote(options.config.gameId)},`,
    `  brandLabel: ${quote(options.config.brandLabel)},`,
    "  live: Object.freeze({",
    `    serverUrl: ${quote(options.config.live.serverUrl)},`,
    `    gamecode: ${quote(options.config.live.gamecode)},`,
    `    rejectQueryParams: Object.freeze(${json(options.config.live.rejectQueryParams)} as const)`,
    "  }),",
    `  supportedSkins: Object.freeze(${json(options.config.supportedSkins)} as const),`,
    "  gameConfig: rawGameConfig,",
    `  reel: Object.freeze(${json(options.config.reel)} as const),`,
    "  skins: Object.freeze({",
    ...options.config.supportedSkins.flatMap((skinId) =>
      renderSkinConfig({
        skinId,
        skin: options.config.skins[skinId],
        names: importNames[skinId],
        modulesName,
      }),
    ),
    "  })",
    "} as const satisfies SlotGameStaticConfig);",
    "",
    `assertSlotGameStaticConfig(${exportName});`,
    "",
  );

  return format(`${lines.join("\n")}`, { parser: "typescript" });
}

export async function generateGameLoadingConfigModule(options: {
  readonly rootDir: string;
  readonly outPath: string;
  readonly config: GameStaticYamlConfig;
}): Promise<string> {
  assertExtension(options.outPath, [".ts"], "--loading-out");
  if (!options.config.loading) {
    throw new Error("game loading 生成需要 YAML loading.resources。");
  }
  const constantPrefix = toConstantName(options.config.gameId);
  const camelPrefix = toCamelName(options.config.gameId);
  const pathResources = options.config.loading.resources.filter(
    isPathLoadingResource,
  );
  const globResources = options.config.loading.resources.filter(
    isGlobLoadingResource,
  );
  const importNames = createLoadingImportNames(options.config);
  const lines: string[] = [
    "// This file is generated by buildgamestatic. Do not edit by hand.",
  ];

  for (const resource of pathResources) {
    lines.push(
      `import ${importNames[resource.id]} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          resource.path,
        )}?url`,
      )};`,
    );
  }

  if (pathResources.length > 0) {
    lines.push("");
  }

  for (const resource of globResources) {
    lines.push(
      `const ${importNames[resource.id]} = import.meta.glob(${quote(
        toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          resource.glob,
        ),
      )}, {`,
      "  eager: true,",
      '  import: "default",',
      '  query: "?url"',
      "}) as Record<string, string>;",
    );
  }

  lines.push(
    "",
    `export interface ${camelPrefix}GeneratedLoadingResourceUrl {`,
    "  readonly id: string;",
    "  readonly url: string;",
    "  readonly kind?: string;",
    "  readonly weight?: number;",
    "}",
    "",
    `export interface ${camelPrefix}GeneratedLoadingGlobGroup {`,
    "  readonly id: string;",
    "  readonly modules: Record<string, string>;",
    "  readonly kind?: string;",
    "  readonly weight?: number;",
    "}",
    "",
    `const ${camelPrefix}LoadingPathResources = Object.freeze([`,
    ...pathResources.map((resource) =>
      renderLoadingPathResource(resource, importNames[resource.id]),
    ),
    `] as const satisfies readonly ${camelPrefix}GeneratedLoadingResourceUrl[]);`,
    "",
    `const ${camelPrefix}LoadingGlobGroups = Object.freeze([`,
    ...globResources.map((resource) =>
      renderLoadingGlobGroup(resource, importNames[resource.id]),
    ),
    `] as const satisfies readonly ${camelPrefix}GeneratedLoadingGlobGroup[]);`,
    "",
    `export const ${constantPrefix}_LOADING_RESOURCE_URLS = Object.freeze(${camelPrefix}CreateGeneratedLoadingResourceUrls());`,
    "",
    `export function ${camelPrefix}CreateGeneratedLoadingResourceUrls(): readonly ${camelPrefix}GeneratedLoadingResourceUrl[] {`,
    `  return ${camelPrefix}ExpandGeneratedLoadingResourceUrls(`,
    `    ${camelPrefix}LoadingPathResources,`,
    `    ${camelPrefix}LoadingGlobGroups,`,
    "  );",
    "}",
    "",
    `export function ${camelPrefix}ExpandGeneratedLoadingResourceUrls(`,
    `  pathResources: readonly ${camelPrefix}GeneratedLoadingResourceUrl[],`,
    `  globGroups: readonly ${camelPrefix}GeneratedLoadingGlobGroup[],`,
    `): readonly ${camelPrefix}GeneratedLoadingResourceUrl[] {`,
    `  const resources: ${camelPrefix}GeneratedLoadingResourceUrl[] = [];`,
    "  const seenIds = new Set<string>();",
    "  const seenUrls = new Set<string>();",
    `  const addResource = (resource: ${camelPrefix}GeneratedLoadingResourceUrl) => {`,
    "    if (seenIds.has(resource.id)) {",
    '      throw new Error(`Duplicate loading resource id "${resource.id}".`);',
    "    }",
    "    seenIds.add(resource.id);",
    "    if (seenUrls.has(resource.url)) {",
    "      return;",
    "    }",
    "    seenUrls.add(resource.url);",
    "    resources.push(Object.freeze(resource));",
    "  };",
    "  for (const resource of pathResources) {",
    "    addResource(resource);",
    "  }",
    "  for (const group of globGroups) {",
    "    const entries = Object.entries(group.modules).sort(([left], [right]) => left.localeCompare(right));",
    "    if (entries.length === 0) {",
    '      throw new Error(`Loading resource glob "${group.id}" matched no files.`);',
    "    }",
    "    const splitWeight = group.weight === undefined ? undefined : group.weight / entries.length;",
    "    for (const [modulePath, url] of entries) {",
    "      addResource({",
    "        id: `${group.id}:${getGeneratedLoadingBaseName(modulePath)}`,",
    "        url,",
    "        ...(group.kind === undefined ? {} : { kind: group.kind }),",
    "        ...(splitWeight === undefined ? {} : { weight: splitWeight }),",
    "      });",
    "    }",
    "  }",
    "  return Object.freeze(resources);",
    "}",
    "",
    "function getGeneratedLoadingBaseName(modulePath: string): string {",
    '  const name = modulePath.split("/").at(-1);',
    "  if (!name) {",
    '    throw new Error(`Cannot derive loading resource basename from "${modulePath}".`);',
    "  }",
    "  return name;",
    "}",
    "",
  );

  return format(`${lines.join("\n")}`, { parser: "typescript" });
}

function renderSkinConfig(options: {
  readonly skinId: string;
  readonly skin: GameStaticYamlSkinConfig;
  readonly names: ImportNames;
  readonly modulesName: string;
}): readonly string[] {
  const { skin, names } = options;
  return [
    `    ${quote(options.skinId)}: Object.freeze({`,
    `      label: ${quote(skin.label)},`,
    "      symbols: Object.freeze({",
    `        manifest: ${names.manifest},`,
    `        pngModules: ${options.modulesName}[${quote(options.skinId)}],`,
    ...(skin.symbols.vniProjectGlob && names.vniProjectModules
      ? [`        vniProjectModules: ${names.vniProjectModules},`]
      : []),
    ...(skin.symbols.vniAssetGlob && names.vniAssetModules
      ? [`        vniAssetModules: ${names.vniAssetModules},`]
      : []),
    `        emptySymbols: Object.freeze(${json(skin.symbols.emptySymbols)} as const),`,
    `        requireExplicitScale: ${String(skin.symbols.requireExplicitScale)},`,
    `        requiredStates: Object.freeze(${json(skin.symbols.requiredStates)} as const)`,
    "      }),",
    "      art: Object.freeze({",
    `        mode: ${quote(skin.art.mode)},`,
    "        variants: Object.freeze({",
    ...renderVariant("landscape", skin.art.variants.landscape, {
      background: names.landscapeBackground,
      conveyor: names.landscapeConveyor,
    }),
    ...renderVariant("portrait", skin.art.variants.portrait, {
      background: names.portraitBackground,
      conveyor: names.portraitConveyor,
    }),
    "        }),",
    `        mainReelBackground: Object.freeze(${renderImageWithUrl(
      skin.art.mainReelBackground,
      names.mainReelBackground,
    )}),`,
    `        reelAreaInMainReelBackground: Object.freeze(${json(
      skin.art.reelAreaInMainReelBackground,
    )} as const)`,
    `      })${skin.featureBars || skin.winAmount ? "," : ""}`,
    ...(skin.featureBars
      ? renderFeatureBarsConfig(skin.featureBars, names)
      : []),
    ...(skin.featureBars && skin.winAmount ? [","] : []),
    ...(skin.winAmount ? renderWinAmountConfig(skin.winAmount, names) : []),
    "    }),",
  ];
}

function renderFeatureBarsConfig(
  featureBars: NonNullable<GameStaticYamlSkinConfig["featureBars"]>,
  names: ImportNames,
): readonly string[] {
  return [
    "      featureBars: Object.freeze({",
    ...Object.entries(featureBars).flatMap(([featureBarId, featureBar]) =>
      renderFeatureBarConfig(
        featureBarId,
        featureBar,
        names.featureBars[featureBarId],
      ),
    ),
    "      })",
  ];
}

function renderFeatureBarConfig(
  featureBarId: string,
  featureBar: GameStaticYamlFeatureBarConfig,
  names: FeatureBarImportNames,
): readonly string[] {
  return [
    `        ${quote(featureBarId)}: Object.freeze({`,
    `          componentName: ${quote(featureBar.componentName)},`,
    `          queueLength: ${numberLiteral(featureBar.queueLength)},`,
    `          visibleCount: ${numberLiteral(featureBar.visibleCount)},`,
    `          terminalSlotIndex: ${numberLiteral(featureBar.terminalSlotIndex)},`,
    `          emptyFeature: ${quote(featureBar.emptyFeature)},`,
    `          allowedFeatures: Object.freeze(${json(featureBar.allowedFeatures)} as const),`,
    "          symbols: Object.freeze({",
    `            manifest: ${names.manifest},`,
    `            pngModules: ${names.symbolModules},`,
    `            requireExplicitScale: ${String(featureBar.symbols.requireExplicitScale)},`,
    `            requiredStates: Object.freeze(${json(featureBar.symbols.requiredStates)} as const)`,
    "          }),",
    "          layout: Object.freeze({",
    `            landscape: Object.freeze(${renderFeatureBarLayoutVariant(
      featureBar.layout.landscape,
    )}),`,
    `            portrait: Object.freeze(${renderFeatureBarLayoutVariant(
      featureBar.layout.portrait,
    )})`,
    "          })",
    "        }),",
  ];
}

function renderFeatureBarLayoutVariant(
  variant: GameStaticYamlFeatureBarConfig["layout"]["landscape"],
): string {
  return `{ movement: ${quote(variant.movement)}, slotRectsInConveyor: Object.freeze(${json(
    variant.slotRectsInConveyor,
  )} as const) } as const`;
}

function renderWinAmountConfig(
  winAmount: NonNullable<GameStaticYamlSkinConfig["winAmount"]>,
  names: ImportNames,
): readonly string[] {
  if (!names.winAmountProjectModules || !names.winAmountAssetModules) {
    throw new Error("winAmount module names are required.");
  }
  return [
    "      winAmount: Object.freeze({",
    `        amountScale: ${numberLiteral(winAmount.amountScale)},`,
    `        currency: ${quote(winAmount.currency)},`,
    `        locale: ${quote(winAmount.locale)},`,
    `        minorCountDurationSeconds: ${numberLiteral(
      winAmount.minorCountDurationSeconds,
    )},`,
    `        majorCountDurationSeconds: ${numberLiteral(
      winAmount.majorCountDurationSeconds,
    )},`,
    `        thresholds: Object.freeze(${json(winAmount.thresholds)} as const),`,
    `        text: Object.freeze(${json(winAmount.text)} as const),`,
    "        layout: Object.freeze({",
    `          minorAnchor: ${quote(winAmount.layout.minorAnchor)},`,
    `          majorAnchor: ${quote(winAmount.layout.majorAnchor)},`,
    `          minorOffset: Object.freeze(${json(
      winAmount.layout.minorOffset,
    )} as const),`,
    `          majorOffset: Object.freeze(${json(
      winAmount.layout.majorOffset,
    )} as const)`,
    "        }),",
    "        animations: Object.freeze({",
    `          projectModules: ${names.winAmountProjectModules},`,
    `          assetModules: ${names.winAmountAssetModules},`,
    `          tiers: Object.freeze(${json(winAmount.animations.tiers)} as const)`,
    "        })",
    "      })",
  ];
}

function renderLoadingPathResource(
  resource: Extract<GameStaticYamlLoadingResource, { readonly path: string }>,
  urlName: string,
): string {
  const fields = [
    `id: ${quote(resource.id)}`,
    `url: ${urlName}`,
    ...renderLoadingOptionalFields(resource),
  ];
  return `  Object.freeze({ ${fields.join(", ")} }),`;
}

function renderLoadingGlobGroup(
  resource: Extract<GameStaticYamlLoadingResource, { readonly glob: string }>,
  modulesName: string,
): string {
  const fields = [
    `id: ${quote(resource.id)}`,
    `modules: ${modulesName}`,
    ...renderLoadingOptionalFields(resource),
  ];
  return `  Object.freeze({ ${fields.join(", ")} }),`;
}

function renderLoadingOptionalFields(
  resource: GameStaticYamlLoadingResource,
): readonly string[] {
  return [
    ...(resource.kind === undefined ? [] : [`kind: ${quote(resource.kind)}`]),
    ...(resource.weight === undefined
      ? []
      : [`weight: ${numberLiteral(resource.weight)}`]),
  ];
}

function renderVariant(
  variantId: "landscape" | "portrait",
  variant: GameStaticYamlArtVariant,
  names: { readonly background: string; readonly conveyor?: string },
): readonly string[] {
  return [
    `          ${variantId}: Object.freeze({`,
    `            background: Object.freeze(${renderImageWithUrl(
      variant.background,
      names.background,
    )}),`,
    `            focusRect: Object.freeze(${json(variant.focusRect)} as const),`,
    `            frameFocusRect: Object.freeze(${json(variant.frameFocusRect)} as const),`,
    ...(variant.minFocusMargin
      ? [
          `            minFocusMargin: Object.freeze(${json(
            variant.minFocusMargin,
          )} as const),`,
        ]
      : []),
    `            mainReelBackgroundPositionInFocusRect: Object.freeze(${json(
      variant.mainReelBackgroundPositionInFocusRect,
    )} as const)`,
    ...(variant.conveyor && names.conveyor
      ? [
          `,`,
          `            conveyor: Object.freeze(${renderConveyorWithUrl(
            variant.conveyor,
            names.conveyor,
          )})`,
        ]
      : []),
    "          }),",
  ];
}

function renderImageWithUrl(
  image: { readonly width: number; readonly height: number },
  urlName: string,
): string {
  return `{ url: ${urlName}, width: ${numberLiteral(image.width)}, height: ${numberLiteral(
    image.height,
  )} } as const`;
}

function renderConveyorWithUrl(
  conveyor: {
    readonly width: number;
    readonly height: number;
    readonly positionInFocusRect: { readonly x: number; readonly y: number };
  },
  urlName: string,
): string {
  return `{ url: ${urlName}, width: ${numberLiteral(
    conveyor.width,
  )}, height: ${numberLiteral(
    conveyor.height,
  )}, positionInFocusRect: Object.freeze(${json(
    conveyor.positionInFocusRect,
  )} as const) } as const`;
}

interface ImportNames {
  readonly manifest: string;
  readonly symbolModules: string;
  readonly vniProjectModules?: string;
  readonly vniAssetModules?: string;
  readonly winAmountProjectModules?: string;
  readonly winAmountAssetModules?: string;
  readonly landscapeBackground: string;
  readonly portraitBackground: string;
  readonly mainReelBackground: string;
  readonly landscapeConveyor?: string;
  readonly portraitConveyor?: string;
  readonly featureBars: Readonly<Record<string, FeatureBarImportNames>>;
}

interface FeatureBarImportNames {
  readonly manifest: string;
  readonly symbolModules: string;
}

function createImportNames(
  config: GameStaticYamlConfig,
): Record<string, ImportNames> {
  return Object.fromEntries(
    config.supportedSkins.map((skinId) => {
      const prefix = `${toCamelName(config.gameId)}Skin${toIdentifierPart(skinId)}`;
      const skin = config.skins[skinId];
      return [
        skinId,
        {
          manifest: `${prefix}SymbolManifest`,
          symbolModules: `${prefix}SymbolModules`,
          vniProjectModules: skin.symbols.vniProjectGlob
            ? `${prefix}VniProjectModules`
            : undefined,
          vniAssetModules: skin.symbols.vniAssetGlob
            ? `${prefix}VniAssetModules`
            : undefined,
          winAmountProjectModules: skin.winAmount
            ? `${prefix}WinAmountProjectModules`
            : undefined,
          winAmountAssetModules: skin.winAmount
            ? `${prefix}WinAmountAssetModules`
            : undefined,
          landscapeBackground: `${prefix}LandscapeBackgroundUrl`,
          portraitBackground: `${prefix}PortraitBackgroundUrl`,
          mainReelBackground: `${prefix}MainReelBackgroundUrl`,
          landscapeConveyor: `${prefix}LandscapeConveyorUrl`,
          portraitConveyor: `${prefix}PortraitConveyorUrl`,
          featureBars: Object.fromEntries(
            Object.keys(skin.featureBars ?? {}).map((featureBarId) => {
              const featurePrefix = `${prefix}${toIdentifierPart(featureBarId)}FeatureBar`;
              return [
                featureBarId,
                {
                  manifest: `${featurePrefix}SymbolManifest`,
                  symbolModules: `${featurePrefix}SymbolModules`,
                },
              ];
            }),
          ),
        },
      ];
    }),
  );
}

function createLoadingImportNames(
  config: GameStaticYamlConfig,
): Record<string, string> {
  return Object.fromEntries(
    (config.loading?.resources ?? []).map((resource, index) => {
      const suffix = isPathLoadingResource(resource) ? "Url" : "Modules";
      return [
        resource.id,
        `${toCamelName(config.gameId)}Loading${toIdentifierPart(resource.id)}${index}${suffix}`,
      ];
    }),
  );
}

function isPathLoadingResource(
  resource: GameStaticYamlLoadingResource,
): resource is Extract<
  GameStaticYamlLoadingResource,
  { readonly path: string }
> {
  return "path" in resource;
}

function isGlobLoadingResource(
  resource: GameStaticYamlLoadingResource,
): resource is Extract<
  GameStaticYamlLoadingResource,
  { readonly glob: string }
> {
  return "glob" in resource;
}

function normalizeOptionPath(rootDir: string, value: string): string {
  return resolve(value) === value ? value.replace(`${rootDir}/`, "") : value;
}

function toConstantName(value: string): string {
  return value.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

function toCamelName(value: string): string {
  const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  return parts
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
}

function toIdentifierPart(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9]+/g, "_");
  if (/^[0-9]/.test(cleaned)) {
    return cleaned;
  }
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

function numberLiteral(value: number): string {
  if (!Number.isFinite(value)) {
    throw new Error("生成数值必须是有限数。");
  }
  return String(value);
}
