import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { format } from "prettier";
import {
  assertExtension,
  findRepoRoot,
  toImportSpecifierFromRoot,
} from "./path-utils.js";
import { loadGameStaticYamlConfig } from "./yaml-loader.js";
import type {
  BuildGameStaticResolvedOptions,
  BuildGameStaticResult,
  GameStaticYamlArtVariant,
  GameStaticYamlConfig,
  GameStaticYamlSkinConfig,
} from "./types.js";

export async function generateGameStaticConfigFile(
  options: BuildGameStaticResolvedOptions,
): Promise<BuildGameStaticResult> {
  assertExtension(options.outPath, [".ts"], "--out");
  const rootDir = resolve(options.rootDir || findRepoRoot());
  const inputPath = normalizeOptionPath(rootDir, options.inputPath);
  const outPath = normalizeOptionPath(rootDir, options.outPath);
  const config = loadGameStaticYamlConfig({ rootDir, inputPath });
  if (config.gameId !== options.gameId) {
    throw new Error(
      `--game 必须与 YAML gameId 一致：${options.gameId} !== ${config.gameId}`,
    );
  }
  const generated = await generateGameStaticConfigModule({
    rootDir,
    outPath: resolve(rootDir, outPath),
    config,
  });
  const absoluteOutPath = resolve(rootDir, outPath);

  if (options.check) {
    const existing = existsSync(absoluteOutPath)
      ? readFileSync(absoluteOutPath, "utf8")
      : "";
    if (existing !== generated) {
      throw new Error(`生成文件不同步：${outPath}`);
    }
    return Object.freeze({
      outputPath: outPath,
      generated,
      changed: false,
      checked: true,
    });
  }

  const existing = existsSync(absoluteOutPath)
    ? readFileSync(absoluteOutPath, "utf8")
    : "";
  mkdirSync(dirname(absoluteOutPath), { recursive: true });
  if (existing !== generated) {
    writeFileSync(absoluteOutPath, generated, "utf8");
  }
  return Object.freeze({
    outputPath: outPath,
    generated,
    changed: existing !== generated,
    checked: false,
  });
}

export async function generateGameStaticConfigModule(options: {
  readonly rootDir: string;
  readonly outPath: string;
  readonly config: GameStaticYamlConfig;
}): Promise<string> {
  const exportName = `${toConstantName(options.config.gameId)}_STATIC_CONFIG`;
  const modulesName = `${toConstantName(options.config.gameId)}_STATIC_SKIN_MODULES`;
  const lines: string[] = [
    "// This file is generated by buildgamestatic. Do not edit by hand.",
    'import { assertSlotGameStaticConfig, type SlotGameStaticConfig } from "@slotclientengine/gameframeworks/static-config";',
    `import rawGameConfig from ${quote(
      toImportSpecifierFromRoot(
        options.rootDir,
        options.outPath,
        options.config.gameConfig,
      ),
    )};`,
  ];
  const importNames = createImportNames(options.config);

  for (const skinId of options.config.supportedSkins) {
    const skin = options.config.skins[skinId];
    const names = importNames[skinId];
    lines.push(
      `import ${names.manifest} from ${quote(
        toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.symbols.manifest,
        ),
      )};`,
      `import ${names.landscapeBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.landscape.background.path,
        )}?url`,
      )};`,
      `import ${names.portraitBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.portrait.background.path,
        )}?url`,
      )};`,
      `import ${names.mainReelBackground} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.mainReelBackground.path,
        )}?url`,
      )};`,
      `import ${names.landscapeConveyor} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.landscape.conveyor.path,
        )}?url`,
      )};`,
      `import ${names.portraitConveyor} from ${quote(
        `${toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.art.variants.portrait.conveyor.path,
        )}?url`,
      )};`,
    );
  }

  lines.push("");
  for (const skinId of options.config.supportedSkins) {
    const names = importNames[skinId];
    const skin = options.config.skins[skinId];
    lines.push(
      `const ${names.symbolModules} = import.meta.glob(${quote(
        toImportSpecifierFromRoot(
          options.rootDir,
          options.outPath,
          skin.symbols.pngGlob,
        ),
      )}, {`,
      "  eager: true,",
      '  import: "default",',
      '  query: "?url"',
      "}) as Record<string, string>;",
    );
  }

  lines.push(
    "",
    `export const ${modulesName} = Object.freeze({`,
    ...options.config.supportedSkins.map((skinId) => {
      const names = importNames[skinId];
      return `  ${quote(skinId)}: ${names.symbolModules}`;
    }),
    "} as const);",
    "",
    `export const ${exportName} = Object.freeze({`,
    "  schemaVersion: 1,",
    `  gameId: ${quote(options.config.gameId)},`,
    `  brandLabel: ${quote(options.config.brandLabel)},`,
    "  live: Object.freeze({",
    `    serverUrl: ${quote(options.config.live.serverUrl)},`,
    `    gamecode: ${quote(options.config.live.gamecode)},`,
    `    rejectQueryParams: Object.freeze(${json(options.config.live.rejectQueryParams)} as const)`,
    "  }),",
    `  supportedSkins: Object.freeze(${json(options.config.supportedSkins)} as const),`,
    "  gameConfig: rawGameConfig,",
    `  reel: Object.freeze(${json(options.config.reel)} as const),`,
    "  skins: Object.freeze({",
    ...options.config.supportedSkins.flatMap((skinId) =>
      renderSkinConfig({
        skinId,
        skin: options.config.skins[skinId],
        names: importNames[skinId],
        modulesName,
      }),
    ),
    "  })",
    "} as const satisfies SlotGameStaticConfig);",
    "",
    `assertSlotGameStaticConfig(${exportName});`,
    "",
  );

  return format(`${lines.join("\n")}`, { parser: "typescript" });
}

function renderSkinConfig(options: {
  readonly skinId: string;
  readonly skin: GameStaticYamlSkinConfig;
  readonly names: ImportNames;
  readonly modulesName: string;
}): readonly string[] {
  const { skin, names } = options;
  return [
    `    ${quote(options.skinId)}: Object.freeze({`,
    `      label: ${quote(skin.label)},`,
    "      symbols: Object.freeze({",
    `        manifest: ${names.manifest},`,
    `        pngModules: ${options.modulesName}[${quote(options.skinId)}],`,
    `        emptySymbols: Object.freeze(${json(skin.symbols.emptySymbols)} as const),`,
    `        requireExplicitScale: ${String(skin.symbols.requireExplicitScale)},`,
    `        requiredStates: Object.freeze(${json(skin.symbols.requiredStates)} as const)`,
    "      }),",
    "      art: Object.freeze({",
    `        mode: ${quote(skin.art.mode)},`,
    `        scenePartGap: ${numberLiteral(skin.art.scenePartGap)},`,
    "        variants: Object.freeze({",
    ...renderVariant("landscape", skin.art.variants.landscape, {
      background: names.landscapeBackground,
      conveyor: names.landscapeConveyor,
    }),
    ...renderVariant("portrait", skin.art.variants.portrait, {
      background: names.portraitBackground,
      conveyor: names.portraitConveyor,
    }),
    "        }),",
    `        mainReelBackground: Object.freeze(${renderImageWithUrl(
      skin.art.mainReelBackground,
      names.mainReelBackground,
    )}),`,
    `        reelWindowInMainReelBackground: Object.freeze(${json(
      skin.art.reelWindowInMainReelBackground,
    )} as const)`,
    "      })",
    "    }),",
  ];
}

function renderVariant(
  variantId: "landscape" | "portrait",
  variant: GameStaticYamlArtVariant,
  names: { readonly background: string; readonly conveyor: string },
): readonly string[] {
  return [
    `          ${variantId}: Object.freeze({`,
    `            background: Object.freeze(${renderImageWithUrl(
      variant.background,
      names.background,
    )}),`,
    `            focusRect: Object.freeze(${json(variant.focusRect)} as const),`,
    `            frameFocusRect: Object.freeze(${json(variant.frameFocusRect)} as const),`,
    ...(variant.minFocusMargin
      ? [
          `            minFocusMargin: Object.freeze(${json(
            variant.minFocusMargin,
          )} as const),`,
        ]
      : []),
    `            conveyor: Object.freeze(${renderConveyorWithUrl(
      variant.conveyor,
      names.conveyor,
    )})`,
    "          }),",
  ];
}

function renderImageWithUrl(
  image: { readonly width: number; readonly height: number },
  urlName: string,
): string {
  return `{ url: ${urlName}, width: ${numberLiteral(image.width)}, height: ${numberLiteral(
    image.height,
  )} } as const`;
}

function renderConveyorWithUrl(
  conveyor: {
    readonly width: number;
    readonly height: number;
    readonly placement: string;
  },
  urlName: string,
): string {
  return `{ url: ${urlName}, width: ${numberLiteral(
    conveyor.width,
  )}, height: ${numberLiteral(conveyor.height)}, placement: ${quote(
    conveyor.placement,
  )} } as const`;
}

interface ImportNames {
  readonly manifest: string;
  readonly symbolModules: string;
  readonly landscapeBackground: string;
  readonly portraitBackground: string;
  readonly mainReelBackground: string;
  readonly landscapeConveyor: string;
  readonly portraitConveyor: string;
}

function createImportNames(
  config: GameStaticYamlConfig,
): Record<string, ImportNames> {
  return Object.fromEntries(
    config.supportedSkins.map((skinId) => {
      const prefix = `${toCamelName(config.gameId)}Skin${toIdentifierPart(skinId)}`;
      return [
        skinId,
        {
          manifest: `${prefix}SymbolManifest`,
          symbolModules: `${prefix}SymbolModules`,
          landscapeBackground: `${prefix}LandscapeBackgroundUrl`,
          portraitBackground: `${prefix}PortraitBackgroundUrl`,
          mainReelBackground: `${prefix}MainReelBackgroundUrl`,
          landscapeConveyor: `${prefix}LandscapeConveyorUrl`,
          portraitConveyor: `${prefix}PortraitConveyorUrl`,
        },
      ];
    }),
  );
}

function normalizeOptionPath(rootDir: string, value: string): string {
  return resolve(value) === value ? value.replace(`${rootDir}/`, "") : value;
}

function toConstantName(value: string): string {
  return value.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

function toCamelName(value: string): string {
  const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  return parts
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
}

function toIdentifierPart(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9]+/g, "_");
  if (/^[0-9]/.test(cleaned)) {
    return cleaned;
  }
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

function numberLiteral(value: number): string {
  if (!Number.isFinite(value)) {
    throw new Error("生成数值必须是有限数。");
  }
  return String(value);
}
